export const Styles = {
    balancePanelValue: {
        fontFamily: 'AldotheApache',
        fontSize: 45,
        fill: 0xffffff,
        align: 'center',
        stroke: '#743f17',
        strokeThickness: 4,
    },
    lackPanelValue: {
        fontFamily: 'AldotheApache',
        fontSize: 25,
        fill: 0xffffff,
        align: 'center',
        stroke: '#743f17',
        strokeThickness: 3,
    },
    lackPanelLevel: {
        fontFamily: 'AldotheApache',
        fontSize: 25,
        fill: 0xffffff,
        align: 'center',
        stroke: '#000000',
        strokeThickness: 1.5,
    },
    roundWinInfoWinValue: {
        fontFamily: 'AldotheApache',
        fontSize: 110,
        align: 'center',
        fill: 0xfcef5e,
        stroke: '#743f17',
        strokeThickness: 3,
    },
    roundWinInfoMultiplierValue: {
        fontFamily: 'AldotheApache',
        fontSize: 50,
        fill: 0xffffff,
        align: 'center'
    },
    roundWinInfoLuckValue: {
        fontFamily: 'AldotheApache',
        fontSize: 50,
        fill: 0xffffff,
        align: 'center',
    },
    grabGoldIconText: {
        fontFamily: 'AldotheApache',
        fontSize: 33,
        fill: 0xfcef5e,
        stroke: '#743f17',
        strokeThickness: 3,
    },
    nextStepWin: {
        fontFamily: 'AldotheApache',
        fontSize: 60,
        fill: 0xfcef5e,
        stroke: '#743f17',
        strokeThickness: 4,
    },
    popupLackWinValue: {
        fontFamily: 'AldotheApache',
        fontSize: 45,
        fill: 0xffffff,
        align: 'center',
        stroke: '#743f17',
        strokeThickness: 2,
    },
    popupTitle: {
        fontFamily: 'AldotheApache',
        fontSize: 45,
        fill: 0xffffff,
        align: 'center',
        stroke: '#743f17',
        strokeThickness: 4,
    },
    loadingProgress: {
        fontFamily: 'AldotheApache',
        fontSize: 45,
        fill: 0x9dd142,
        align: 'center',
        stroke: '#000000',
        strokeThickness: 1,
    },
    PlayBtnText: {
        fontFamily: 'AldotheApache',
        fontSize: 45,
        fill: 0xffffff,
        align: 'center',
        stroke: '#000000',
        strokeThickness: 1,
    },
    BottomPanelBtnDefaultText: {
        fontFamily: 'AldotheApache',
        fontSize: 20,
        fill: 0xAA4D00,
        align: 'center',
    },
    BottomPanelBtnActiveText: {
        fontFamily: 'AldotheApache',
        fontSize: 20,
        fill: 0xffffff,
        align: 'center',
    },
    TasksPanelBtnText: {
        fontFamily: 'AldotheApache',
        fontSize: 27,
        fill: 0xffffff,
        align: 'center',
    },
    TaskInfoText: {
        fontFamily: 'AldotheApache',
        fontSize: 36,
        wordWrapWidth: 400,
        wordWrap: true,
        fill: 0xffffff,
    },
    ClaimBtnText: {
        fontFamily: 'AldotheApache',
        fontSize: 27,
        fontWeight: 400,
        fill: 0xffffff,
        align: 'center',
    },
    TaskCardDescriptionText: {
        fontFamily: 'AldotheApache',
        fontSize: 27,
        fill: 0xffffff,
        align: 'center',
        wordWrapWidth: 400,
        wordWrap: true,
    }
};
